language: python
python:
  - "3.8"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install yaqd-fakes

jobs:
  include:
    - &pytest
      stage: test
      name: "pytest-nightly"
      python: nightly
      script:
      - coverage run -m pytest  # Run the tests and check for test coverage.
      - coverage report -m  # Generate test coverage report.
      - codecov  # Upload the report to codecov.
    - <<: *pytest
      name: "pytest-3.8"
      python: 3.8
    - <<: *pytest
      name: "pytest-3.7"
      python: 3.7
    - stage: test
      install: skip
      name: "flake8"
      script:
      - flake8
    - stage: deploy
      name: "docs"
      script:
      - make -C docs html  # Build the documentation.
    - stage: deploy
      name: "twine"
      script:
      - echo "todo: actually release with twine"

deploy:
  on:
    tags: true
