language: python
python:
  - "3.8"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install yaqd-fakes

jobs:
  include:
    - stage: test
      name: "pytest"
      python:
        - "3.7"
	- "3.8"
	- "nightly"
      script:
      - coverage run -m pytest  # Run the tests and check for test coverage.
      - coverage report -m  # Generate test coverage report.
      - codecov  # Upload the report to codecov.
    - stage: test
      name: "flake8"
      script:
      - flake8
    - stage: deploy
      name: "docs"
      on: tags: true
      script:
      - make -C docs html  # Build the documentation.
    - stage: deploy
      name: "twine"
      on: tags: true
      script:
      - echo "todo: actually release with twine"
